
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class HaChiCfg : Luban.BeanBase
{
    public HaChiCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["skill"].IsString) { throw new SerializationException(); }  Skill = _buf["skill"]; }
        { if(!_buf["frame"].IsNumber) { throw new SerializationException(); }  Frame = _buf["frame"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
    }

    public static HaChiCfg DeserializeHaChiCfg(JSONNode _buf)
    {
        return new HaChiCfg(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 角色名
    /// </summary>
    public readonly string Name;
    public readonly string Skill;
    /// <summary>
    /// 帧数
    /// </summary>
    public readonly int Frame;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
   
    public const int __ID__ = -1160768615;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "skill:" + Skill + ","
        + "frame:" + Frame + ","
        + "damage:" + Damage + ","
        + "}";
    }
}

}

