
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class StoryTable
{
    private readonly System.Collections.Generic.List<StoryCfg> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), StoryCfg> _dataMapUnion;

    public StoryTable(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<StoryCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StoryCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StoryCfg.DeserializeStoryCfg(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), StoryCfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Index), _v);
        }
    }

    public System.Collections.Generic.List<StoryCfg> DataList => _dataList;

    public StoryCfg Get(int id, int index) => _dataMapUnion.TryGetValue((id, index), out StoryCfg __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

