
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public PropTable PropTable {get; }
    public ExampleTable ExampleTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        PropTable = new PropTable(loader("proptable"));
        ExampleTable = new ExampleTable(loader("exampletable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        PropTable.ResolveRef(this);
        ExampleTable.ResolveRef(this);
    }
}

}
